//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.239
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honememo.Wptscs.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Honememo.Wptscs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Translation Support for Wikipedia Ver{0}.{1:D2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!-- {0}, [[:{1}:{2}]] ({3}(UTC)) --&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArticleFooter {
            get {
                return ResourceManager.GetString("ArticleFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (load failed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropDownConfigLoadConfigFailed {
            get {
                return ResourceManager.GetString("DropDownConfigLoadConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time: {0:m\:ss} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load settings failed.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageConfigLordFailed {
            get {
                return ResourceManager.GetString("ErrorMessageConfigLordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not found. Please check installed file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageConfigNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save settings failed.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageConfigSaveFailed {
            get {
                return ResourceManager.GetString("ErrorMessageConfigSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection failed. Please check network configuration or server status.
        ///({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageConnectionFailed {
            get {
                return ResourceManager.GetString("ErrorMessageConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected exception.
        ///
        ///&lt;Error detail&gt;
        ///{0}
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageDevelopmentError {
            get {
                return ResourceManager.GetString("ErrorMessageDevelopmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeadingViewHeaderText {
            get {
                return ResourceManager.GetString("HeadingViewHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Completed. Result: {0}, Log: {1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageEnd {
            get {
                return ResourceManager.GetString("LogMessageEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not supported page name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageErrorPageName {
            get {
                return ResourceManager.GetString("LogMessageErrorPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageErrorURL {
            get {
                return ResourceManager.GetString("LogMessageErrorURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Output {0} failed. ({1})
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageFileSaveFailed {
            get {
                return ResourceManager.GetString("LogMessageFileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [[{1}]] from {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageGetTargetArticle {
            get {
                return ResourceManager.GetString("LogMessageGetTargetArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interlanguage is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageInterWikiNotFound {
            get {
                return ResourceManager.GetString("LogMessageInterWikiNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageLinkArticleNotFound {
            get {
                return ResourceManager.GetString("LogMessageLinkArticleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    *cache に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageNoteTranslation {
            get {
                return ResourceManager.GetString("LogMessageNoteTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redirect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageRedirect {
            get {
                return ResourceManager.GetString("LogMessageRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}, {1:F}
        ///
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageStart {
            get {
                return ResourceManager.GetString("LogMessageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find interlanguage start. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageStartParseAndReplace {
            get {
                return ResourceManager.GetString("LogMessageStartParseAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///Process stopped. Log: {0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageStop {
            get {
                return ResourceManager.GetString("LogMessageStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning: This page have interlanguage to [[{0}]]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageTargetArticleHadInterWiki {
            get {
                return ResourceManager.GetString("LogMessageTargetArticleHadInterWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page is not found. Please check title. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageTargetArticleNotFound {
            get {
                return ResourceManager.GetString("LogMessageTargetArticleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identify {{{{{0}}}}}&apos;s namespace failed. {1} is guessed. ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogMessageTemplateNameUnidentified {
            get {
                return ResourceManager.GetString("LogMessageTemplateNameUnidentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This page have interlanguage to [[{0}]]. Does it continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuestionMessageArticleExisted {
            get {
                return ResourceManager.GetString("QuestionMessageArticleExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Question に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   → に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RightArrow {
            get {
                return ResourceManager.GetString("RightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating caches... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusCacheUpdating {
            get {
                return ResourceManager.GetString("StatusCacheUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusConfigReading {
            get {
                return ResourceManager.GetString("StatusConfigReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusDownloading {
            get {
                return ResourceManager.GetString("StatusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusFileWriting {
            get {
                return ResourceManager.GetString("StatusFileWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parsing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusParsing {
            get {
                return ResourceManager.GetString("StatusParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusPinging {
            get {
                return ResourceManager.GetString("StatusPinging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output caches failed.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageCacheSaveFailed {
            get {
                return ResourceManager.GetString("WarningMessageCacheSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language code is already. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageDuplicateCodeColumn {
            get {
                return ResourceManager.GetString("WarningMessageDuplicateCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name is already. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageDuplicateConfigName {
            get {
                return ResourceManager.GetString("WarningMessageDuplicateConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language code is already. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageDuplicateLanguageCode {
            get {
                return ResourceManager.GetString("WarningMessageDuplicateLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input title. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageEmptyArticle {
            get {
                return ResourceManager.GetString("WarningMessageEmptyArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language code may not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageEmptyCodeColumn {
            get {
                return ResourceManager.GetString("WarningMessageEmptyCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name may not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageEmptyConfigName {
            get {
                return ResourceManager.GetString("WarningMessageEmptyConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input language code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageEmptyLanguageCode {
            get {
                return ResourceManager.GetString("WarningMessageEmptyLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select output folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageEmptySaveDirectory {
            get {
                return ResourceManager.GetString("WarningMessageEmptySaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source&apos;s code, title and Destination&apos;s code may not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageEmptyTranslationDictionary {
            get {
                return ResourceManager.GetString("WarningMessageEmptyTranslationDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source and Destination may not be same. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageEqualsSourceAndTarget {
            get {
                return ResourceManager.GetString("WarningMessageEqualsSourceAndTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cache expire must be greater than or equal to 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageIgnoreCacheExpire {
            get {
                return ResourceManager.GetString("WarningMessageIgnoreCacheExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect retry time must be greater than or equal to 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageIgnoreConnectRetryTime {
            get {
                return ResourceManager.GetString("WarningMessageIgnoreConnectRetryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max connect retries must be greater than or equal to 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageIgnoreMaxConnectRetries {
            get {
                return ResourceManager.GetString("WarningMessageIgnoreMaxConnectRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Namespace&apos;s ID must be integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageIgnoreNumericNamespace {
            get {
                return ResourceManager.GetString("WarningMessageIgnoreNumericNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output folder is missing or invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageIgnoreSaveDirectory {
            get {
                return ResourceManager.GetString("WarningMessageIgnoreSaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name is invalid.
        ///
        ///Invalid chars : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageInvalidConfigName {
            get {
                return ResourceManager.GetString("WarningMessageInvalidConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select source. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageNotSelectedSource {
            get {
                return ResourceManager.GetString("WarningMessageNotSelectedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select destination. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageNotSelectedTarget {
            get {
                return ResourceManager.GetString("WarningMessageNotSelectedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name may not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageShortNameColumnOnly {
            get {
                return ResourceManager.GetString("WarningMessageShortNameColumnOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bracket style must be empty or contains string &quot;$1&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageUnformatedBracket {
            get {
                return ResourceManager.GetString("WarningMessageUnformatedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timestamp must be empty or date. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningMessageUnformatedTimestamp {
            get {
                return ResourceManager.GetString("WarningMessageUnformatedTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
