//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honememo.Wptscs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Translation Support for Wikipedia/{0}.{1:D2}")]
        public string DefaultUserAgent {
            get {
                return ((string)(this["DefaultUserAgent"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveDirectory {
            get {
                return ((string)(this["SaveDirectory"]));
            }
            set {
                this["SaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string LastSelectedSource {
            get {
                return ((string)(this["LastSelectedSource"]));
            }
            set {
                this["LastSelectedSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedTarget {
            get {
                return ((string)(this["LastSelectedTarget"]));
            }
            set {
                this["LastSelectedTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAgent {
            get {
                return ((string)(this["UserAgent"]));
            }
            set {
                this["UserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Referer {
            get {
                return ((string)(this["Referer"]));
            }
            set {
                this["Referer"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsi=\"http://www.w3.o" +
            "rg/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <str" +
            "ing>CURRENTYEAR</string>\n  <string>CURRENTMONTH</string>\n  <string>CURRENTMONTHN" +
            "AME</string>\n  <string>CURRENTMONTHNAMEGEN</string>\n  <string>CURRENTMONTHABBREV" +
            "</string>\n  <string>CURRENTDAY</string>\n  <string>CURRENTDAY2</string>\n  <string" +
            ">CURRENTDOW</string>\n  <string>CURRENTDAYNAME</string>\n  <string>CURRENTTIME</st" +
            "ring>\n  <string>CURRENTHOUR</string>\n  <string>CURRENTWEEK</string>\n  <string>CU" +
            "RRENTTIMESTAMP</string>\n  <string>LOCALYEAR</string>\n  <string>LOCALMONTH</strin" +
            "g>\n  <string>LOCALMONTHNAME</string>\n  <string>LOCALMONTHNAMEGEN</string>\n  <str" +
            "ing>LOCALMONTHABBREV</string>\n  <string>LOCALDAY</string>\n  <string>LOCALDAY2</s" +
            "tring>\n  <string>LOCALDOW</string>\n  <string>LOCALDAYNAME</string>\n  <string>LOC" +
            "ALTIME</string>\n  <string>LOCALHOUR</string>\n  <string>LOCALWEEK</string>\n  <str" +
            "ing>LOCALTIMESTAMP</string>\n  <string>SITENAME</string>\n  <string>SERVER</string" +
            ">\n  <string>SERVERNAME</string>\n  <string>DIRMARK</string>\n  <string>DIRECTIONMA" +
            "RK</string>\n  <string>SCRIPTPATH</string>\n  <string>STYLEPATH</string>\n  <string" +
            ">CURRENTVERSION</string>\n  <string>CONTENTLANGUAGE</string>\n  <string>CONTENTLAN" +
            "G</string>\n  <string>REVISIONID</string>\n  <string>REVISIONDAY</string>\n  <strin" +
            "g>REVISIONDAY2</string>\n  <string>REVISIONMONTH</string>\n  <string>REVISIONYEAR<" +
            "/string>\n  <string>REVISIONTIMESTAMP</string>\n  <string>REVISIONUSER</string>\n  " +
            "<string>PAGESIZE</string>\n  <string>PROTECTIONLEVEL</string>\n  <string>DISPLAYTI" +
            "TLE</string>\n  <string>DEFAULTSORT</string>\n  <string>DEFAULTSORTKEY</string>\n  " +
            "<string>DEFAULTCATEGORYSORT</string>\n  <string>NUMBEROFPAGES</string>\n  <string>" +
            "NUMBEROFARTICLES</string>\n  <string>NUMBEROFFILES</string>\n  <string>NUMBEROFEDI" +
            "TS</string>\n  <string>NUMBEROFVIEWS</string>\n  <string>NUMBEROFUSERS</string>\n  " +
            "<string>NUMBEROFADMINS</string>\n  <string>NUMBEROFACTIVEUSERS</string>\n  <string" +
            ">PAGESINCATEGORY</string>\n  <string>PAGESINCAT</string>\n  <string>NUMBERINGROUP<" +
            "/string>\n  <string>NUMINGROUP</string>\n  <string>PAGESINNS</string>\n  <string>PA" +
            "GESINNAMESPACE</string>\n  <string>FULLPAGENAME</string>\n  <string>PAGENAME</stri" +
            "ng>\n  <string>BASEPAGENAME</string>\n  <string>SUBPAGENAME</string>\n  <string>SUB" +
            "JECTPAGENAME</string>\n  <string>TALKPAGENAME</string>\n  <string>FULLPAGENAMEE</s" +
            "tring>\n  <string>PAGENAMEE</string>\n  <string>BASEPAGENAMEE</string>\n  <string>S" +
            "UBPAGENAMEE</string>\n  <string>SUBJECTPAGENAMEE</string>\n  <string>TALKPAGENAMEE" +
            "</string>\n  <string>NAMESPACE</string>\n  <string>SUBJECTSPACE</string>\n  <string" +
            ">ARTICLESPACE</string>\n  <string>TALKSPACE</string>\n  <string>NAMESPACEE</string" +
            ">\n  <string>SUBJECTSPACEE</string>\n  <string>TALKSPACEE</string>\n  <string>local" +
            "url</string>\n  <string>fullurl</string>\n  <string>filepath</string>\n  <string>ur" +
            "lencode</string>\n  <string>anchorencode</string>\n  <string>ns</string>\n  <string" +
            ">lc</string>\n  <string>lcfirst</string>\n  <string>uc</string>\n  <string>ucfirst<" +
            "/string>\n  <string>formatnum</string>\n  <string>#dateformat</string>\n  <string>#" +
            "formatdate</string>\n  <string>padleft</string>\n  <string>padright</string>\n  <st" +
            "ring>plural</string>\n  <string>grammar</string>\n  <string>int</string>\n  <string" +
            ">#language</string>\n  <string>#special</string>\n  <string>#tag</string>\n  <strin" +
            "g>gender</string>\n  <string>groupconvert</string>\n  <string>#expr</string>\n  <st" +
            "ring>#if</string>\n  <string>#ifeq</string>\n  <string>#ifexist</string>\n  <string" +
            ">#ifexpr</string>\n  <string>#switch</string>\n  <string>#time</string>\n  <string>" +
            "#rel2abs</string>\n  <string>#titleparts</string>\n  <string>#iferror</string>\n</A" +
            "rrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MediaWikiMagicWords {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MediaWikiMagicWords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/w/api.php?action=query&prop=revisions&titles=$1&redirects&rvprop=timestamp|conte" +
            "nt&format=xml")]
        public string MediaWikiContentApi {
            get {
                return ((string)(this["MediaWikiContentApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" ($1) ")]
        public string Bracket {
            get {
                return ((string)(this["Bracket"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MediaWikiTemplateNamespace {
            get {
                return ((int)(this["MediaWikiTemplateNamespace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int MediaWikiCategoryNamespace {
            get {
                return ((int)(this["MediaWikiCategoryNamespace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int MediaWikiFileNamespace {
            get {
                return ((int)(this["MediaWikiFileNamespace"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.00:00:00")]
        public global::System.TimeSpan CacheExpire {
            get {
                return ((global::System.TimeSpan)(this["CacheExpire"]));
            }
            set {
                this["CacheExpire"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.20.0.0")]
        public string ConfigurationCompatible {
            get {
                return ((string)(this["ConfigurationCompatible"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/w/api.php?format=xml&action=query&meta=siteinfo&siprop=namespaces|namespacealias" +
            "es|interwikimap")]
        public string MediaWikiMetaApi {
            get {
                return ((string)(this["MediaWikiMetaApi"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUpgraded {
            get {
                return ((bool)(this["IsUpgraded"]));
            }
            set {
                this["IsUpgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreError {
            get {
                return ((bool)(this["IgnoreError"]));
            }
            set {
                this["IgnoreError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaxConnectRetries {
            get {
                return ((int)(this["MaxConnectRetries"]));
            }
            set {
                this["MaxConnectRetries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RequestInterval {
            get {
                return ((int)(this["RequestInterval"]));
            }
            set {
                this["RequestInterval"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsi=\"http://www.w3.o" +
            "rg/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n  <str" +
            "ing>acronym</string>\n  <string>advogato</string>\n  <string>annotationwiki</strin" +
            "g>\n  <string>arxiv</string>\n  <string>c2find</string>\n  <string>cache</string>\n " +
            " <string>commons</string>\n  <string>corpknowpedia</string>\n  <string>dictionary<" +
            "/string>\n  <string>disinfopedia</string>\n  <string>docbook</string>\n  <string>do" +
            "i</string>\n  <string>drumcorpswiki</string>\n  <string>dwjwiki</string>\n  <string" +
            ">emacswiki</string>\n  <string>elibre</string>\n  <string>foldoc</string>\n  <strin" +
            "g>foxwiki</string>\n  <string>freebsdman</string>\n  <string>gej</string>\n  <strin" +
            "g>gentoo-wiki</string>\n  <string>google</string>\n  <string>googlegroups</string>" +
            "\n  <string>hammondwiki</string>\n  <string>hewikisource</string>\n  <string>hrwiki" +
            "</string>\n  <string>imdb</string>\n  <string>jargonfile</string>\n  <string>jspwik" +
            "i</string>\n  <string>keiki</string>\n  <string>kmwiki</string>\n  <string>linuxwik" +
            "i</string>\n  <string>lojban</string>\n  <string>lqwiki</string>\n  <string>lugkr</" +
            "string>\n  <string>mathsongswiki</string>\n  <string>meatball</string>\n  <string>m" +
            "ediazilla</string>\n  <string>mediawikiwiki</string>\n  <string>memoryalpha</strin" +
            "g>\n  <string>metawiki</string>\n  <string>metawikipedia</string>\n  <string>moinmo" +
            "in</string>\n  <string>mozillawiki</string>\n  <string>mw</string>\n  <string>oeis<" +
            "/string>\n  <string>openfacts</string>\n  <string>openwiki</string>\n  <string>patw" +
            "iki</string>\n  <string>pmeg</string>\n  <string>ppr</string>\n  <string>pythoninfo" +
            "</string>\n  <string>rfc</string>\n  <string>s23wiki</string>\n  <string>seattlewik" +
            "i</string>\n  <string>seattlewireless</string>\n  <string>senseislibrary</string>\n" +
            "  <string>slashdot</string>\n  <string>sourceforge</string>\n  <string>squeak</str" +
            "ing>\n  <string>susning</string>\n  <string>svgwiki</string>\n  <string>tavi</strin" +
            "g>\n  <string>tejo</string>\n  <string>tmbw</string>\n  <string>tmnet</string>\n  <s" +
            "tring>tmwiki</string>\n  <string>theopedia</string>\n  <string>twiki</string>\n  <s" +
            "tring>uea</string>\n  <string>unreal</string>\n  <string>usemod</string>\n  <string" +
            ">vinismo</string>\n  <string>webseitzwiki</string>\n  <string>why</string>\n  <stri" +
            "ng>wiki</string>\n  <string>wikia</string>\n  <string>wikibooks</string>\n  <string" +
            ">wikicities</string>\n  <string>wikif1</string>\n  <string>wikihow</string>\n  <str" +
            "ing>wikinfo</string>\n  <string>wikimedia</string>\n  <string>wikinews</string>\n  " +
            "<string>wikiquote</string>\n  <string>wikipedia</string>\n  <string>wikisource</st" +
            "ring>\n  <string>wikispecies</string>\n  <string>wikitravel</string>\n  <string>wik" +
            "iversity</string>\n  <string>wikt</string>\n  <string>wiktionary</string>\n  <strin" +
            "g>wlug</string>\n  <string>zwiki</string>\n  <string>zzz wiki</string>\n</ArrayOfSt" +
            "ring>")]
        public global::System.Collections.Specialized.StringCollection MediaWikiInterwikiPrefixs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MediaWikiInterwikiPrefixs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedLanguage {
            get {
                return ((string)(this["LastSelectedLanguage"]));
            }
            set {
                this["LastSelectedLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wikipedia")]
        public string LastSelectedConfiguration {
            get {
                return ((string)(this["LastSelectedConfiguration"]));
            }
            set {
                this["LastSelectedConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".xml")]
        public string ConfigurationExtension {
            get {
                return ((string)(this["ConfigurationExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/w/api.php?action=query&prop=langlinks&titles=$1&redirects=&lllimit=500&format=xm" +
            "l")]
        public string MediaWikiInterlanguageApi {
            get {
                return ((string)(this["MediaWikiInterlanguageApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://{0}.wikipedia.org")]
        public string WikipediaLocation {
            get {
                return ((string)(this["WikipediaLocation"]));
            }
        }
    }
}
