//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4200
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honememo.Wptscs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config.xml")]
        public string ConfigurationFile {
            get {
                return ((string)(this["ConfigurationFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WikipediaTranslationSupportTool/{0}.{1:D2}")]
        public string DefaultUserAgent {
            get {
                return ((string)(this["DefaultUserAgent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://{0}.wikipedia.org")]
        public string WikipediaLocation {
            get {
                return ((string)(this["WikipediaLocation"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveDirectory {
            get {
                return ((string)(this["SaveDirectory"]));
            }
            set {
                this["SaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string LastSelectedSource {
            get {
                return ((string)(this["LastSelectedSource"]));
            }
            set {
                this["LastSelectedSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedTarget {
            get {
                return ((string)(this["LastSelectedTarget"]));
            }
            set {
                this["LastSelectedTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAgent {
            get {
                return ((string)(this["UserAgent"]));
            }
            set {
                this["UserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Referer {
            get {
                return ((string)(this["Referer"]));
            }
            set {
                this["Referer"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>CURRENTDAY</string>\r\n  <string>CURRENTDAY2</string>\r\n  <string>CURRENTDAYN" +
            "AME</string>\r\n  <string>CURRENTDOW</string>\r\n  <string>CURRENTMONTH</string>\r\n  " +
            "<string>CURRENTMONTHABBREV</string>\r\n  <string>CURRENTMONTHNAME</string>\r\n  <str" +
            "ing>CURRENTTIME</string>\r\n  <string>CURRENTHOUR</string>\r\n  <string>CURRENTWEEK<" +
            "/string>\r\n  <string>CURRENTYEAR</string>\r\n  <string>CURRENTTIMESTAMP</string>\r\n " +
            " <string>CURRENTVERSION</string>\r\n  <string>NUMBEROFEDITS</string>\r\n  <string>NU" +
            "MBEROFEDITS:R</string>\r\n  <string>NUMBEROFARTICLES</string>\r\n  <string>NUMBEROFA" +
            "RTICLES:R</string>\r\n  <string>NUMBEROFPAGES</string>\r\n  <string>NUMBEROFPAGES:R<" +
            "/string>\r\n  <string>NUMBEROFFILES</string>\r\n  <string>NUMBEROFFILES:R</string>\r\n" +
            "  <string>NUMBEROFUSERS</string>\r\n  <string>NUMBEROFUSERS:R</string>\r\n  <string>" +
            "NUMBEROFACTIVEUSERS</string>\r\n  <string>NUMBEROFACTIVEUSERS:R</string>\r\n  <strin" +
            "g>NUMBEROFADMINS</string>\r\n  <string>NUMBEROFADMINS:R</string>\r\n  <string>NUMBER" +
            "INGROUP:groupname</string>\r\n  <string>NUMBERINGROUP:groupname|R</string>\r\n  <str" +
            "ing>NUMBERINGROUP:bureaucrat|R</string>\r\n  <string>PAGESINNAMESPACE</string>\r\n  " +
            "<string>PAGESINNS:ns</string>\r\n  <string>PAGESINNS:ns|R</string>\r\n  <string>PAGE" +
            "NAME</string>\r\n  <string>PAGENAMEE</string>\r\n  <string>BASEPAGENAME</string>\r\n  " +
            "<string>BASEPAGENAMEE</string>\r\n  <string>SUBPAGENAME</string>\r\n  <string>SUBPAG" +
            "ENAMEE</string>\r\n  <string>NAMESPACE</string>\r\n  <string>NAMESPACEE</string>\r\n  " +
            "<string>FULLPAGENAME</string>\r\n  <string>FULLPAGENAMEE</string>\r\n  <string>TALKS" +
            "PACE</string>\r\n  <string>TALKSPACEE</string>\r\n  <string>SUBJECTSPACE</string>\r\n " +
            " <string>SUBJECTSPACEE</string>\r\n  <string>ARTICLESPACE</string>\r\n  <string>ARTI" +
            "CLESPACEE</string>\r\n  <string>TALKPAGENAME</string>\r\n  <string>TALKPAGENAMEE</st" +
            "ring>\r\n  <string>SUBJECTPAGENAME</string>\r\n  <string>SUBJECTPAGENAMEE</string>\r\n" +
            "  <string>ARTICLEPAGENAME</string>\r\n  <string>ARTICLEPAGENAMEE</string>\r\n  <stri" +
            "ng>REVISIONID</string>\r\n  <string>REVISIONDAY</string>\r\n  <string>REVISIONDAY2</" +
            "string>\r\n  <string>REVISIONMONTH</string>\r\n  <string>REVISIONYEAR</string>\r\n  <s" +
            "tring>REVISIONTIMESTAMP</string>\r\n  <string>SITENAME</string>\r\n  <string>SERVER<" +
            "/string>\r\n  <string>SCRIPTPATH</string>\r\n  <string>SERVERNAME</string>\r\n  <strin" +
            "g>PAGESINCATEGORY:category</string>\r\n  <string>PAGESINCATEGORY:category|R</strin" +
            "g>\r\n  <string>PAGESINCATEGORY:User en|R</string>\r\n  <string>PAGESINCAT:category<" +
            "/string>\r\n  <string>PAGESINCAT:category|R</string>\r\n  <string>PAGESINCAT:User en" +
            "|R</string>\r\n  <string>PAGESIZE:page</string>\r\n  <string>PAGESIZE:page|R</string" +
            ">\r\n  <string>PAGESIZE:Help:Magic_words|R</string>\r\n  <string>GENDER:username|TEX" +
            "TIFMALE|TEXTIFFEMALE|TEXTIFUNSPECIFIED</string>\r\n  <string>CONTENTLANGUAGE</stri" +
            "ng>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MediaWikiMagicWordsVariables {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MediaWikiMagicWordsVariables"]));
            }
        }
    }
}
