# GitHub ActionsによるCI自動テスト設定。
# masterブランチがpushまたはプルリク更新されたタイミングで自動テストを流す。
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v6

      # msbuildをパスに登録
      - uses: microsoft/setup-msbuild@v3

      # NuGetの取得
      - run: nuget restore "./Wikipedia 翻訳支援ツール.sln"

      # ビルドの実行
      - run: msbuild "./Wikipedia 翻訳支援ツール.sln"

      # ユニットテストの実行
      - run: pwsh -File .github/scripts/test.ps1
        timeout-minutes: 3
