# GitHub ActionsによるCI自動テスト設定。
# masterブランチがpushまたはプルリク更新されたタイミングで自動テストを流す
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  dotnet-test:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3

      # 依存関係の解消
      - run: dotnet restore "./Wikipedia 翻訳支援ツール.sln"

      # .NETユニットテストの実行
      - run: dotnet test "./Wikipedia 翻訳支援ツール.sln" --no-restore
        timeout-minutes: 3
